spring.application.name=literalura

# 1. Conexión a la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST}/literalura
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de Hibernate / JPA
# 'update' creará las tablas automáticamente basándose en tus clases Java
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en la consola para que puedas debuguear fácilmente
spring.jpa.show-sql=true
# Formatea el SQL para que sea legible en la consola
spring.jpa.format_sql=true